### ISSUE TITLE
Chrome bug when opening certain images

### ISSUE THREAD

**Issue by 1byte2bytes** [Wikia/vignette#86]
There appears to be a bug where people using Chrome get a 404 when opening some images.

Opening [this image](http://img4.wikia.nocookie.net/__cb20110706223436/mlp/images/archive/8/80/20120214110652!Twilight_starting_to_get_very_angry_S1E15.png) on Chrome well get a message saying to go here and on Firefox I can see the image. [See here](http://i.imgur.com/3hxpYBk.png)

I am using Chrome Version 43.0.2357.81 (64-bit) and Firefox 38.0.1 (64-bit) for Mac OS X 10.10.3.

**Comment by harnash** [comment]
This issue seems to be fixed already.
